CREATE TABLE IF NOT EXISTS bad_case_record (
    id BIGINT NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT NOT NULL DEFAULT 1,
    case_code VARCHAR(64) NOT NULL,
    source_type VARCHAR(32) NOT NULL,
    stage VARCHAR(32) NOT NULL,
    badcase_type VARCHAR(64) NOT NULL,
    severity VARCHAR(16) NOT NULL,
    project_name VARCHAR(128) DEFAULT NULL,
    requirement_title VARCHAR(256) DEFAULT NULL,
    input_prompt MEDIUMTEXT DEFAULT NULL,
    generated_prd MEDIUMTEXT DEFAULT NULL,
    generated_code MEDIUMTEXT DEFAULT NULL,
    expected_behavior MEDIUMTEXT DEFAULT NULL,
    failure_reason MEDIUMTEXT DEFAULT NULL,
    reviewed_by VARCHAR(64) DEFAULT NULL,
    pipeline_id BIGINT DEFAULT NULL,
    stage_run_id BIGINT DEFAULT NULL,
    batch_id BIGINT DEFAULT NULL,
    feedback_id BIGINT DEFAULT NULL,
    approval_id BIGINT DEFAULT NULL,
    tags VARCHAR(512) DEFAULT NULL,
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_bad_case_code (case_code),
    KEY idx_bad_case_tenant_stage (tenant_id, stage, create_time),
    KEY idx_bad_case_stage (stage, create_time),
    KEY idx_bad_case_type (badcase_type),
    KEY idx_bad_case_source (source_type),
    KEY idx_bad_case_pipeline (pipeline_id, stage_run_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
