CREATE TABLE IF NOT EXISTS ai_output_governance_record (
    id BIGINT NOT NULL AUTO_INCREMENT,
    record_code VARCHAR(64) NOT NULL,
    source_type VARCHAR(64) NOT NULL DEFAULT 'AUTOMATION_PIPELINE',
    pipeline_id BIGINT DEFAULT NULL,
    stage_run_id BIGINT DEFAULT NULL,
    generation_job_id BIGINT DEFAULT NULL,
    stage_key VARCHAR(64) DEFAULT NULL,
    artifact_type VARCHAR(64) NOT NULL,
    artifact_path VARCHAR(1024) DEFAULT NULL,
    artifact_summary TEXT DEFAULT NULL,
    model_code VARCHAR(64) DEFAULT NULL,
    governance_status VARCHAR(32) NOT NULL DEFAULT 'NEEDS_REVIEW',
    risk_level VARCHAR(32) NOT NULL DEFAULT 'LOW',
    risk_score INT DEFAULT 0,
    policy_snapshot MEDIUMTEXT DEFAULT NULL,
    metadata_json MEDIUMTEXT DEFAULT NULL,
    input_tokens INT DEFAULT NULL,
    output_tokens INT DEFAULT NULL,
    total_tokens INT DEFAULT NULL,
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_ai_output_record_code (record_code),
    KEY idx_ai_output_pipeline (pipeline_id, create_time),
    KEY idx_ai_output_stage (stage_run_id),
    KEY idx_ai_output_type (artifact_type, create_time),
    KEY idx_ai_output_risk (risk_level, governance_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ai_output_governance_policy_template (
    id BIGINT NOT NULL AUTO_INCREMENT,
    policy_code VARCHAR(64) NOT NULL,
    policy_name VARCHAR(128) NOT NULL,
    description TEXT DEFAULT NULL,
    category VARCHAR(64) NOT NULL DEFAULT 'security',
    severity VARCHAR(32) NOT NULL DEFAULT 'MAJOR',
    target_artifact_type VARCHAR(64) NOT NULL DEFAULT 'CODE',
    detector_type VARCHAR(64) NOT NULL DEFAULT 'REGEX',
    config_json MEDIUMTEXT DEFAULT NULL,
    block_on_match TINYINT NOT NULL DEFAULT 1,
    status TINYINT NOT NULL DEFAULT 1,
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_ai_policy_template_code (policy_code),
    KEY idx_ai_policy_template_status (status, category),
    KEY idx_ai_policy_template_target (target_artifact_type, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
